### ISSUE TITLE
elasticsearch crashes with the 7.17.1 image tag

### ISSUE THREAD

**Issue by amimimor** [erikbrgr/conductor-es7-postgres#1]
Hi, running `04.run-local.sh` blows elastic with exception: 
```
docker-elasticsearch-1     | "stacktrace": ["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: cannot downgrade a node from version [7.17.4] to version [7.17.1]"
```
updating the elasticsearch image in the compose file to 7.17.4 fixes that although I have no idea what requires the 7.17.4 image.
btw, this is the first time I was able to run Conductor on my M1 Mac so I want to thank you very very much

**Comment by erikbrgr** [comment]
Hi amimimor,

Fascinating. It might have something to do with you running on a M1 Mac, as the script works fine under Windows. When I have time, I'll update to 7.17.4 myself and test it, then update the scripts accordingly. Thanks for taking the time to point this out!

And awesome to hear you got Conductor working this way. Happy to help!

**Comment by amimimor** [comment]
I hope I'm not going overboard here but I'm now facing another issue where Conductor is oddly trying to connect to postgres with "conductor" as user. My version of your `docker-compose-postgres.yaml` is this:
```
version: '2.3'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal

  conductor-server:
    depends_on:
      - postgres
    environment:
      - CONFIG_PROP=config-postgres.properties
      - ELASTICSEARCH_URL=http://es:9200
      - POSTGRES_ADDRPORT=postgres:5432/db06
      - DB_USER=postgres
      - DB_PASSWORD=postgres
volumes:
  db:
    driver: local
```

and btw, another question if I may, on production environments, etc, how can one pass conductor user/password other then using config files or environment variables?
